import QtQuick 2.1
import qb.components 1.0
import qb.base 1.0;
import FileIO 1.0

App {
  id : app

// ---- Properties

// -------- Define the tile and the screen

  property url titleURL : "ToonHomeWizardTile.qml"
  property ToonHomeWizardTile homeWizardTile

  property url homeWizardScreen1URL : "ToonHomeWizardScreen1.qml"
  property ToonHomeWizardScreen1 homeWizardScreen1

  property url homeWizardScreen2URL : "ToonHomeWizardScreen2.qml"
  property ToonHomeWizardScreen2 homeWizardScreen2

// -------- Control properties

  // used to (de)activate app.log messages
  property bool debug : false     // Errors and testing

  // goes true when tile is installed and enables Timers
  property bool activeMe : false // Tile not installed -> use no CPU

  property int activeScreen : 1 // tile activates this screen

// -------- Properties in userSettingsFile

// Location of settings file

  FileIO {
    id: userSettingsFile
    source : "file:///mnt/data/tsc/toonHomeWizard.userSettings.json"
   }

// Values fixed, collected, calculated or entered by you on the screen

  property variant deviceIP : []
  property variant deviceName : []
  property variant deviceActive : []
  property variant deviceVisible : []
  property variant deviceSwitchEnable : []
  property variant deviceKWHYesterday : [] // today=current-yesterday
  property variant deviceKWHLastWeek : []  // week=current-last week
  property variant deviceKWHLastMonth : []  // month=current-last mont
  property variant deviceKWHOffset : []
  property int kWhDecimals : 3 // 0..3 on APP setup screen

  property string deviceKWHYesterdayDate: "unknown" // detect day change

// Settings on the settings screen

  // Tile format options ( only selected option value is saved )
  property int tileFormatAlwaysRing : 0
  property int tileFormatSegmentedRing: 1
  property int tileFormatWholeRing : 2
  property int tileFormat : tileFormatSegmentedRing

  // Default ring color, change green intensity on the settings screen
  property string tileRingColor : "#00A000"

  // P1 Meter data on tile options (only selected option value is saved)

  property int homeWizardDataOnTileLogo : 0
  property int homeWizardDataOnTileText : 1
  property int homeWizardDataOnTileNow : 2
  property int homeWizardDataOnTileP1Meter : 3
  property int homeWizardDataOnTileP1MeterBatteryLevel : 4
  property int homeWizardDataOnTile : homeWizardDataOnTileLogo

  // kWh column options  ( only selected option value is saved )
  property int kWhToday : 1
  property int kWhWeek : 2 // week is monday..sunday
  property int kWhMonth : 3
  property int kWhMinOffset : 4
  property int kWhTotal : 5
  property int kWhColumn : kWhToday

  // Default signal strength, true = dBm, false = %
  property bool wifidBm : true

  // Battery data
  property bool batteriesInApp : false // setup enables and disables this

  property variant batteryIP : [] // IP and Token have same index
  property variant batteryToken : [] // A token is generated by creating a user in the battery

  // IP address may be reused / changed and a token may be generated for the physical device
  property variant batteryTokenHistory : [] // all tokens ever generated

  property variant batteryName : []
  property variant batteryActive : []
  property variant batteryVisible : []

  property variant batteryKWHImportYesterday : [] // today=current-yesterday
  property variant batteryKWHImportLastWeek : []  // week=current-last week
  property variant batteryKWHImportLastMonth : []  // month=current-last mont
  property variant batteryKWHImportOffset : []

  property variant batteryKWHExportYesterday : [] // today=current-yesterday
  property variant batteryKWHExportLastWeek : []  // week=current-last week
  property variant batteryKWHExportLastMonth : []  // month=current-last mont
  property variant batteryKWHExportOffset : []

  property int batterykWhDecimals : 3 // 0..3 on APP setup screen

  property int batterykWhColumn : kWhToday

  property bool batterywifidBm : true

// User settings read from settings file

  property variant userSettingsJSON : {}

  // when more devices have the same IP address we only collect the first
  // afterwards we copy these values to the others with the same IP

  property int first_index

// -------- Fixed and live properties

  property string errorColor : "#FF0000"

// The data collection Timer interval is different for tile and screen

  property int syncSlow : 60  // fixed in seconds
  property int syncFast : 10  // fixed in seconds
  property int syncIntervalms // actual interval in ms

  property bool settingsActive : false // when active, timers do nothing
//  onSettingsActiveChanged: { debug && log("New value settingsActive: "+settingsActive) }

  // The timers control which HomeWizard device is polled for data
  property int index_device_reading

// live data from the devices

  property variant dataFromDeviceJSON

  property variant deviceOke : []
  property variant deviceOn : []

  property variant deviceWatts : []
  property variant deviceKWH : []
  property variant device_wifi : [] // wifi_strength level in %

  property variant batteryOke : []

  property variant batteryLevel : []
  property variant batteryWatts : []
  property variant batteryKWHImport : []
  property variant batteryKWHExport : []
  property variant battery_wifi : [] // wifi_strength level in %

// ---- Functions General

// -------- A function to log to the console with timestamps

  function log(tolog) {

    var now    = new Date();
    var dateTime = now.getFullYear() + '-' +
        ('00'+(now.getMonth() + 1)   ).slice(-2) + '-' +
        ('00'+ now.getDate()         ).slice(-2) + ' ' +
        ('00'+ now.getHours()        ).slice(-2) + ":" +
        ('00'+ now.getMinutes()      ).slice(-2) + ":" +
        ('00'+ now.getSeconds()      ).slice(-2) + "." +
        ('000'+now.getMilliseconds() ).slice(-3);

// This is a line with the name of the app in it so I can filter the log
    console.log(dateTime+' toonHomeWizard : ' + tolog.toString())

  }

// -------- Handy debug function dumps object properties

function dumpProperties(obj, desc) {
    log("=== dumpProperties ===")
    for (var key in obj) {
        try {
            var value = obj[key]
            if (typeof value === "function") {
                log(desc + " : " + key + " = <functie>")
                log(desc + "    name   = " + value.name)
                log(desc + "    params = " + value.length)
                log(desc + "    source = " + value.toString())
            }
            else {
                log(desc + " : " + key + " type = " + typeof value)
                log(desc + " : " + key + " = " + value)
            }
        }
        catch(e) {
            log(desc + " : " + key + " = <error>")
        }
    }
    log("=== dump end ===")
}

// -------- Register the tile and the screen

  function init() {
    const args = {
      thumbCategory : "general",
      thumbLabel : "HomeWizard",
      thumbIcon : "qrc:/tsc/button_on.png",
      thumbIconVAlignment : "center",
      thumbWeight : 30
    }
    registry.registerWidget("tile", titleURL, this, "homeWizardTile", args);
    registry.registerWidget("screen", homeWizardScreen1URL, this, "homeWizardScreen1");
    registry.registerWidget("screen", homeWizardScreen2URL, this, "homeWizardScreen2");
  }

// -------- At startup initialise data, read saved data and settings

  Component.onCompleted: {
    // init default values
    var ii = 0
    for (ii = 0; ii < 10 ; ii++) {
      deviceIP.push( "0.0.0.0" )
      if (ii < 8 ) {
        // 0..7 are for Energy Sockets
        deviceName.push( "Energy Socket " + ( ii + 1 ) ) // Default name
      } else {
        // 8 and 9 are for import and export of P1 Meter
        deviceName.push( "P1 Meter ")
      }
      deviceKWHYesterday.push( 0.0 )
      deviceKWHLastWeek.push( 0.0 )
      deviceKWHLastMonth.push( 0.0 )
      deviceKWHOffset.push( 0.0 )
      deviceKWH.push( 0.0 )             // we did not read anything yet
      deviceActive.push( false )        // no ip yet so not active
      deviceVisible.push( false )       // visible when true
      deviceSwitchEnable.push( true )   // disabled when false
      deviceOke.push( true )            // assume communication is oke
      deviceOn.push( false )            // assume devices are off
      deviceWatts.push( 0.0 )           // we did not read anything yet
      device_wifi.push( 0.0 )           // we did not read anything yet
    }

    for (ii = 0; ii < 4 ; ii++) {
      batteryIP.push( "0.0.0.0" )
      batteryToken.push ( "0123456789ABCDEF0123456789ABCDEF" )
      batteryName.push( "Battery " + ( ii + 1 ) ) // Default name
      batteryKWHImportYesterday.push( 0.0 )
      batteryKWHImportLastWeek.push( 0.0 )
      batteryKWHImportLastMonth.push( 0.0 )
      batteryKWHImportOffset.push( 0.0 )
      batteryKWHExportYesterday.push( 0.0 )
      batteryKWHExportLastWeek.push( 0.0 )
      batteryKWHExportLastMonth.push( 0.0 )
      batteryKWHExportOffset.push( 0.0 )
      batteryKWHImport.push( 0.0 )             // we did not read anything yet
      batteryKWHExport.push( 0.0 )             // we did not read anything yet
      batteryActive.push( false )        // no ip yet so not active
      batteryVisible.push( false )       // visible when true
      batteryOke.push( true )            // assume communication is oke
      batteryLevel.push( 0.0 )           // we did not read anything yet
      batteryWatts.push( 0.0 )           // we did not read anything yet
      battery_wifi.push( 0.0 )           // we did not read anything yet
    }

    // read user settings ( first time fails and we save defaults )
    try {
      userSettingsJSON = JSON.parse(userSettingsFile.read());

      if ('deviceIP' in userSettingsJSON ) { deviceIP = userSettingsJSON['deviceIP'] }
      if ('deviceName' in userSettingsJSON ) { deviceName = userSettingsJSON['deviceName'] }
      if ('deviceActive' in userSettingsJSON ) { deviceActive = userSettingsJSON['deviceActive'] }
      if ('deviceVisible' in userSettingsJSON ) { deviceVisible = userSettingsJSON['deviceVisible'] }
      if ('deviceSwitchEnable' in userSettingsJSON ) { deviceSwitchEnable = userSettingsJSON['deviceSwitchEnable'] }
      if ('tileFormat' in userSettingsJSON ) { tileFormat = userSettingsJSON['tileFormat'] }
      if ('tileRingColor' in userSettingsJSON ) { tileRingColor = userSettingsJSON['tileRingColor'] }
      if ('wifidBm' in userSettingsJSON ) { wifidBm = userSettingsJSON['wifidBm'] }
      if ('kWhColumn' in userSettingsJSON ) { kWhColumn = userSettingsJSON['kWhColumn'] }
      if ('deviceKWHYesterday' in userSettingsJSON ) { deviceKWHYesterday = userSettingsJSON['deviceKWHYesterday'] }
      if ('deviceKWHLastWeek' in userSettingsJSON ) { deviceKWHLastWeek = userSettingsJSON['deviceKWHLastWeek'] }
      if ('deviceKWHLastMonth' in userSettingsJSON ) { deviceKWHLastMonth = userSettingsJSON['deviceKWHLastMonth'] }
      if ('deviceKWHYesterdayDate' in userSettingsJSON ) { deviceKWHYesterdayDate = userSettingsJSON['deviceKWHYesterdayDate'] }
      if ('deviceKWHOffset' in userSettingsJSON ) { deviceKWHOffset = userSettingsJSON['deviceKWHOffset'] }
      if ('homeWizardDataOnTile' in userSettingsJSON ) { homeWizardDataOnTile = userSettingsJSON['homeWizardDataOnTile'] }
      if ('kWhDecimals' in userSettingsJSON ) { kWhDecimals = userSettingsJSON['kWhDecimals'] }

      if ('batteriesInApp' in userSettingsJSON ) { batteriesInApp = userSettingsJSON['batteriesInApp'] }
      if ('batteryIP' in userSettingsJSON ) { batteryIP = userSettingsJSON['batteryIP'] }
      if ('batteryToken' in userSettingsJSON ) { batteryToken = userSettingsJSON['batteryToken'] }
      if ('batteryTokenHistory' in userSettingsJSON ) { batteryTokenHistory = userSettingsJSON['batteryTokenHistory'] }
      if ('batteryName' in userSettingsJSON ) { batteryName = userSettingsJSON['batteryName'] }
      if ('batteryActive' in userSettingsJSON ) { batteryActive = userSettingsJSON['batteryActive'] }
      if ('batteryVisible' in userSettingsJSON ) { batteryVisible = userSettingsJSON['batteryVisible'] }
      if ('batterykWhColumn' in userSettingsJSON ) { batterykWhColumn = userSettingsJSON['batterykWhColumn'] }
      if ('batteryKWHImportYesterday' in userSettingsJSON ) { batteryKWHImportYesterday = userSettingsJSON['batteryKWHImportYesterday'] }
      if ('batteryKWHImportLastWeek' in userSettingsJSON ) { batteryKWHImportLastWeek = userSettingsJSON['batteryKWHImportLastWeek'] }
      if ('batteryKWHImportLastMonth' in userSettingsJSON ) { batteryKWHImportLastMonth = userSettingsJSON['batteryKWHImportLastMonth'] }
      if ('batteryKWHImportOffset' in userSettingsJSON ) { batteryKWHImportOffset = userSettingsJSON['batteryKWHImportOffset'] }
      if ('batteryKWHExportYesterday' in userSettingsJSON ) { batteryKWHExportYesterday = userSettingsJSON['batteryKWHExportYesterday'] }
      if ('batteryKWHExportLastWeek' in userSettingsJSON ) { batteryKWHExportLastWeek = userSettingsJSON['batteryKWHExportLastWeek'] }
      if ('batteryKWHExportLastMonth' in userSettingsJSON ) { batteryKWHExportLastMonth = userSettingsJSON['batteryKWHExportLastMonth'] }
      if ('batteryKWHExportOffset' in userSettingsJSON ) { batteryKWHExportOffset = userSettingsJSON['batteryKWHExportOffset'] }
      if ('batterykWhDecimals' in userSettingsJSON ) { batterykWhDecimals = userSettingsJSON['batterykWhDecimals'] }
      if ('batterywifidBm' in userSettingsJSON ) { batterywifidBm = userSettingsJSON['batterywifidBm'] }

    } catch(e) {
      saveSettings()
    }
    syncIntervalms = syncSlow * 1000
    // Glonal XMLHttpRequest objects to work around qml memory leak
    initXMLHttpRequests()
  }

// -------- Functions to save data and user settings

  function saveDeviceKWHHistory(){
    // called by timer
    // checks if day and week totals have to be updated for save
    var today = new Date();
    var strDate=today.getFullYear()+'-'+(today.getMonth()+1)+'-'+today.getDate()
    if (strDate != deviceKWHYesterdayDate) {
// each new day save deviceKWHYesterday
      debug && log("Copy Day and Week Counters and save Data")
      deviceKWHYesterdayDate = strDate
      var ii = 0
      for (ii = 0; ii < 10 ; ii++) {
        deviceKWHYesterday[ii] = deviceKWH[ii]
        if ( ii < 4 ) {
          batteryKWHImportYesterday[ii] = batteryKWHImport[ii]
          batteryKWHExportYesterday[ii] = batteryKWHExport[ii]
        }
        if (today.getDay() == 1 ) {
// each new monday also save deviceKWHLastWeek
          deviceKWHLastWeek[ii] = deviceKWH[ii]
          if ( ii < 4 ) {
            batteryKWHImportLastWeek[ii] = batteryKWHImport[ii]
            batteryKWHExportLastWeek[ii] = batteryKWHExport[ii]
          }
        }
        if (today.getDate() == 1 ) {
// each new month also save deviceKWHLastMonth
          deviceKWHLastMonth[ii] = deviceKWH[ii]
          if ( ii < 4 ) {
            batteryKWHImportLastMonth[ii] = batteryKWHImport[ii]
            batteryKWHExportLastMonth[ii] = batteryKWHExport[ii]
          }
        }
      }
      saveSettings()
    }
  }

  function saveSettings(){
    if (activeMe) {
      var tmpUserSettingsJSON = {
        "deviceIP" : deviceIP,
        "deviceName" : deviceName,
        "deviceActive" : deviceActive,
        "deviceVisible" : deviceVisible,
        "kWhColumn" : kWhColumn,
        "deviceKWHYesterday" : deviceKWHYesterday,
        "deviceKWHLastWeek" : deviceKWHLastWeek,
        "deviceKWHLastMonth" : deviceKWHLastMonth,
        "deviceKWHYesterdayDate" : deviceKWHYesterdayDate,
        "deviceKWHOffset" : deviceKWHOffset,
        "kWhDecimals" : kWhDecimals,
        "deviceSwitchEnable" : deviceSwitchEnable,
        "wifidBm" : wifidBm,
        "tileFormat" : tileFormat,
        "tileRingColor" : tileRingColor,
        "homeWizardDataOnTile" : homeWizardDataOnTile,

        "batteriesInApp" : batteriesInApp,
        "batteryIP" : batteryIP,
        "batteryToken" : batteryToken,
        "batteryTokenHistory" : batteryTokenHistory,
        "batteryName" : batteryName,
        "batteryActive" : batteryActive,
        "batteryVisible" : batteryVisible,
        "batterykWhColumn" : batterykWhColumn,

        "batteryKWHImportYesterday" : batteryKWHImportYesterday,
        "batteryKWHImportLastWeek" : batteryKWHImportLastWeek,
        "batteryKWHImportLastMonth" : batteryKWHImportLastMonth,
        "batteryKWHImportOffset" : batteryKWHImportOffset,

        "batteryKWHExportYesterday" : batteryKWHExportYesterday,
        "batteryKWHExportLastWeek" : batteryKWHExportLastWeek,
        "batteryKWHExportLastMonth" : batteryKWHExportLastMonth,
        "batteryKWHExportOffset" : batteryKWHExportOffset,

        "batterykWhDecimals" : batterykWhDecimals,
        "batterywifidBm" : batterywifidBm,
      }
      var doc3 = new XMLHttpRequest();
      doc3.open("PUT", userSettingsFile.source);
      doc3.send(JSON.stringify(tmpUserSettingsJSON));
    }
  }

// ---- Functions for HomeWizard communication

// -------- Functions for XMLHttpRequests

  property variant xhrGetData
  property variant xhrGetDataJsonResponse
  property int xhrGetDataCurrentIndex
  property bool xhrGetDataBusy : false

  property variant xhrGetState
  property variant xhrGetStateJsonResponse
  property int xhrGetStateCurrentIndex
  property bool xhrGetStateBusy : false

  property variant xhrMoveSwitch
  property variant xhrMoveSwitchJsonResponse
  property int xhrMoveSwitchCurrentIndex
  property bool xhrMoveSwitchBusy : false

  Timer {
    id : getHomeWizardDataTimeoutTimer
    interval : 2000 // timeout of 2 seconds
    running : false
    repeat : false
    onTriggered: {
      deviceOke[xhrGetDataCurrentIndex] = false
      log("Error Timeout Get Data: " +
        xhrGetDataCurrentIndex + " " +
        deviceIP[xhrGetDataCurrentIndex] +
        " Device: " + deviceName[xhrGetDataCurrentIndex])
      xhrGetData.abort()
      Qt.callLater(function() { xhrGetDataBusy = false })
    }
  }

  Timer {
    id : getHomeWizardStateTimeoutTimer
    interval : 4000 // timeout of 4 seconds
    running : false
    repeat : false
    onTriggered: {
      deviceOke[xhrGetStateCurrentIndex] = false
      log("Error Timeout Get State: " +
        xhrGetStateCurrentIndex + " " +
        deviceIP[xhrGetStateCurrentIndex] +
        " Device: " + deviceName[xhrGetStateCurrentIndex])
      xhrGetState.abort()
      Qt.callLater(function() { xhrGetStateBusy = false })
    }
  }

  function initXMLHttpRequests() {
    // create 3 global objects : xhrGetData, xhrGetState and xhrMoveSwitch

    xhrGetData = new XMLHttpRequest();

    xhrGetData.onreadystatechange = function() {
      if( xhrGetData.readyState === 4){
        if (xhrGetData.status === 200 || xhrGetData.status === 300  || xhrGetData.status === 302) {
          // we got an answer in time so stop the timeout timer
          getHomeWizardDataTimeoutTimer.stop()
          xhrGetDataJsonResponse = JSON.parse(xhrGetData.responseText);
          try {
            deviceWatts[xhrGetDataCurrentIndex] = xhrGetDataJsonResponse['active_power_w']
            device_wifi[xhrGetDataCurrentIndex] = xhrGetDataJsonResponse['wifi_strength']
            deviceKWH[xhrGetDataCurrentIndex] = xhrGetDataJsonResponse['total_power_import_kwh']
            // when deviceKWHYesterday, LastWeek and Month are 0 they have to start from now
            if ( deviceKWHYesterday[xhrGetDataCurrentIndex] == 0 ) { deviceKWHYesterday[xhrGetDataCurrentIndex] = deviceKWH[xhrGetDataCurrentIndex] }
            if ( deviceKWHLastWeek[xhrGetDataCurrentIndex]  == 0 ) { deviceKWHLastWeek[xhrGetDataCurrentIndex]  = deviceKWH[xhrGetDataCurrentIndex] }
            if ( deviceKWHLastMonth[xhrGetDataCurrentIndex]  == 0 ){ deviceKWHLastMonth[xhrGetDataCurrentIndex]  = deviceKWH[xhrGetDataCurrentIndex] }

            if (xhrGetDataCurrentIndex == 8) {
              // this is the P1 Meter with a 2nd KWH field for export which is in 'xhrGetDataCurrentIndex + 1'
              deviceKWH[xhrGetDataCurrentIndex+1] = xhrGetDataJsonResponse['total_power_export_kwh']
              // when deviceKWHYesterday, LastWeek and Month are 0 they have to start from now
              if ( deviceKWHYesterday[xhrGetDataCurrentIndex + 1] == 0 ) { deviceKWHYesterday[xhrGetDataCurrentIndex + 1] = deviceKWH[xhrGetDataCurrentIndex + 1] }
              if (  deviceKWHLastWeek[xhrGetDataCurrentIndex + 1] == 0 ) { deviceKWHLastWeek[xhrGetDataCurrentIndex + 1] = deviceKWH[xhrGetDataCurrentIndex + 1] }
              if (  deviceKWHLastMonth[xhrGetDataCurrentIndex + 1] == 0 ){ deviceKWHLastMonth[xhrGetDataCurrentIndex + 1] = deviceKWH[xhrGetDataCurrentIndex + 1] }
            }
            deviceOke[xhrGetDataCurrentIndex] = true
          } catch(e) {
            log("Error Get Data: " + xhrGetDataCurrentIndex + " " + deviceIP[xhrGetDataCurrentIndex] + " Device: " + deviceName[xhrGetDataCurrentIndex]+" ; "+e);
            deviceOke[xhrGetDataCurrentIndex] = false
          }
        }else{
          log("xhrGetData fault response: " + xhrGetDataCurrentIndex + " " + deviceIP[xhrGetDataCurrentIndex] + " Device: " + deviceName[xhrGetDataCurrentIndex]+ " ; " + xhrGetData.status + " ; "  + xhrGetData.responseText)
        }
        Qt.callLater(function() { xhrGetDataBusy = false })
      }
    }

    xhrGetState = new XMLHttpRequest();

    xhrGetState.onreadystatechange = function() {
      if( xhrGetState.readyState === 4){
        if (xhrGetState.status === 200 || xhrGetState.status === 300  || xhrGetState.status === 302) {
          // we got an answer in time so stop the timeout timer
          getHomeWizardStateTimeoutTimer.stop()
          xhrGetStateJsonResponse= JSON.parse(xhrGetState.responseText)
          if ('power_on' in xhrGetStateJsonResponse ) {
            deviceOn[xhrGetStateCurrentIndex] = xhrGetStateJsonResponse['power_on']
          } else {
            log("xhrGetStateJsonResponse ERROR " + xhrGetStateCurrentIndex + " " + deviceIP[xhrGetStateCurrentIndex] + " Device: " + deviceName[xhrGetStateCurrentIndex])
          }
        }else{
          log("xhrGetState fault response: "  + xhrGetStateCurrentIndex + " " + deviceIP[xhrGetStateCurrentIndex] + " Device: " + deviceName[xhrGetStateCurrentIndex] + " ; " + xhrGetState.status + " ; "  + xhrGetState.responseText)
        }
        Qt.callLater(function() { xhrGetStateBusy = false })
      }
    }

    xhrMoveSwitch = new XMLHttpRequest();

    xhrMoveSwitch.onreadystatechange = function() {
      if( xhrMoveSwitch.readyState === 4){
        if (xhrMoveSwitch.status === 200 || xhrMoveSwitch.status === 300  || xhrMoveSwitch.status === 302) {
          xhrMoveSwitchJsonResponse= JSON.parse(xhrMoveSwitch.responseText)
          if ('power_on' in xhrMoveSwitchJsonResponse ) {
            deviceOn[xhrMoveSwitchCurrentIndex] = xhrMoveSwitchJsonResponse['power_on']
            homeWizardScreen1.updateScreenData()
          } else {
            log("xhrMoveSwitchJsonResponse ERROR " + xhrMoveSwitchCurrentIndex + " " + deviceIP[xhrMoveSwitchCurrentIndex] + " Device: " + deviceName[xhrMoveSwitchCurrentIndex])
          }
        }else{
          log("xhrMoveSwitch fault response: "  + xhrMoveSwitchCurrentIndex + " " + deviceIP[xhrMoveSwitchCurrentIndex] + " Device: " + deviceName[xhrMoveSwitchCurrentIndex] + " ; "  + xhrMoveSwitch.status + " ; "  + xhrMoveSwitch.responseText)
        }
        Qt.callLater(function() {xhrMoveSwitchBusy = false })
      }
    }

  }

// -------- Function getHomeWizard

  function getHomeWizardData(index_device) {
    // get the data

    // find first active device for this IP address
    first_index = deviceIP.indexOf(deviceIP[index_device])
    while ( ( ! deviceActive[first_index] )  && (first_index > -1 ) ) {
      first_index = deviceIP.indexOf(deviceIP[index_device], first_index + 1)
    }

    if ( ( first_index < index_device ) && deviceActive[first_index] ) {
      // we leave this function and copy the data later from first_index
      debug && log("Skip Extra Data Collection for: "+index_device)
    } else {
      if (xhrGetDataBusy) {
        log("xhrGetData  is busy for device: "+xhrGetDataCurrentIndex+" "+deviceIP[xhrGetDataCurrentIndex] + "  " + deviceName[xhrGetDataCurrentIndex])
      } else {
        xhrGetDataBusy = true
        // tell index_device to xhrGetData.onreadystatechange
        xhrGetDataCurrentIndex = index_device
        xhrGetData.open("GET", "http://"+deviceIP[index_device]+"/api/v1/data", true);
        xhrGetData.send();
        // we may not get an answer in time so start the timeout timer
        getHomeWizardDataTimeoutTimer.start()
      }
    }
  }

  function getHomeWizardState(index_device) {
    // get power switch state

    // find first active device for this IP address
    if ( deviceOke[xhrGetDataCurrentIndex] ) {
      first_index = deviceIP.indexOf(deviceIP[index_device])
      if ( ( first_index < index_device ) && deviceActive[first_index] ) {
      // we leave this function and copy the data later from first_index
        debug && log("Skip Extra State Collection for: "+index_device)
      } else {
        if (xhrGetStateBusy) {
          log("xhrGetState is busy for device: "+xhrGetStateCurrentIndex+" "+deviceIP[xhrGetStateCurrentIndex] + "  " + deviceName[xhrGetStateCurrentIndex])
        } else {
          xhrGetStateBusy = true
          xhrGetStateCurrentIndex = index_device
          xhrGetState.open("GET", "http://"+deviceIP[index_device]+"/api/v1/state", true);
          xhrGetState.send();
        // we may not get an answer in time so start the timeout timer
          getHomeWizardStateTimeoutTimer.start()
        }
      }
    }
  }

// -------- Function switchHomeWizard

  function switchHomeWizard(index_device) {
    if (xhrMoveSwitchBusy) {
      log("xhrMoveSwitch is busy for device: "+xhrMoveSwitchCurrentIndex+" "+deviceIP[xhrMoveSwitchCurrentIndex] + "  " + deviceName[xhrMoveSwitchCurrentIndex])
    } else {
      xhrMoveSwitchCurrentIndex = index_device
      xhrMoveSwitchBusy = true
      xhrMoveSwitch.open("PUT", "http://"+deviceIP[index_device]+"/api/v1/state", true);
      xhrMoveSwitch.setRequestHeader("Content-Type", "application/json");
      xhrMoveSwitch.send(JSON.stringify({ "power_on": deviceOn[index_device] }));
    }
  }

// ---- Timers and function to change Main Timer interval

// -------- Data collection Timer, started by Main Timer, stops itself

//  activated each syncIntervalms by startGetHomeWizardsTimerTimer

  property bool ignoringErrors : true

  Timer {
    id : getHomeWizardsTimer
    interval : 500
    running : false
    repeat : true
    triggeredOnStart : true
    onTriggered: {

      if ( ! activeMe ) { getHomeWizardsTimer.stop() } // stop myself
      // NOTE: to allow XMLHttpRequest to finish it runs 15 times.

      if ( settingsActive ) { index_device_reading = 15 } // force data collection stop

      // skip inactive devices
      while ( ( ! deviceActive[index_device_reading] ) && (index_device_reading < 9)  ) {
        index_device_reading = index_device_reading + 1 ;
      }

      // Only devices 0..8, not 9 which is P1 Meter export which comes with 8
      if (index_device_reading < 9) {

        if (deviceOke[index_device_reading] || ignoringErrors) {
          // ignoringErrors is true every other run to allow devices which
          //   are not oke to retry and become ok
          getHomeWizardData(index_device_reading)
          // 9 is a P1 Meter and has no power button
          if (index_device_reading < 8 ) {
            getHomeWizardState(index_device_reading)
          }
        }
      } else {
        // All device data requests are running but maybe not completed
        // so I loop some more before I process data and stop myself.
        if (index_device_reading == 15) {

          var index_device
          for (index_device = 1 ; index_device < 8; index_device++ ) {
            if (deviceActive[index_device]) {
              first_index = deviceIP.indexOf(deviceIP[index_device])
              while ( ( ! deviceActive[first_index] )  && (first_index > -1 ) ) {
                first_index = deviceIP.indexOf(deviceIP[index_device], first_index + 1)
              }
              if ( first_index > -1 ) {
                if ( ( first_index < index_device ) && deviceActive[first_index] ) {
                  debug && log("Copy Data from: "+first_index+ " to: "+index_device)
                  deviceWatts[index_device] = deviceWatts[first_index]
                  device_wifi[index_device] = device_wifi[first_index]
                  deviceKWH[index_device] = deviceKWH[first_index]
                  deviceKWHYesterday[index_device] = deviceKWHYesterday[first_index]
                  deviceKWHLastWeek[index_device] = deviceKWHLastWeek[first_index]
                  deviceKWHLastMonth[index_device] = deviceKWHLastMonth[first_index]
                  deviceOn[index_device] = deviceOn[first_index]
                }
              }
            }
          }
          homeWizardTile.updateTileData()
          homeWizardScreen1.updateScreenData()
          saveDeviceKWHHistory()
          getHomeWizardsTimer.stop() // stop myself
          debug && log("Stopped getHomeWizardsTimer")
        }
      }
      index_device_reading = index_device_reading + 1 ;
    }
  }

// -------- Main Timer to start data collection Timer each interval

// Main Timer in ms syncIntervalms

  Timer {
    id: startGetHomeWizardsTimerTimer
    interval: syncIntervalms
    running: activeMe // Tile not installed -> do not run -> no CPU waste
    repeat: true
    triggeredOnStart: true
    onTriggered: {
      if ( ! settingsActive ) {
        if (getHomeWizardsTimer.running) {
          debug && log("Skip getHomeWizardsTimer")
        } else {
          ignoringErrors = ! ignoringErrors
          index_device_reading = 0 ;
          getHomeWizardsTimer.start()
          debug && log("Started getHomeWizardsTimer")
        }
      }
    }
  }

// -------- Function to change Main Timer interval

  function startGetHomeWizardsTimerTimerSpeed(NewInterval) {
    startGetHomeWizardsTimerTimer.stop()
    syncIntervalms = NewInterval * 1000
    startGetHomeWizardsTimerTimer.start()
  }

// ---- Functions for HomeWizard Batteries

  FileIO {
    id: controlFile
   }

  property string triggerFile : "file:///tmp/tsc.command" // write triggerText
  property string triggerText : "external-toonHomeWizard"
  property string cmdFile : "file:///tmp/toonHomeWizardBatteries.cmd"
  property string lstFile : "file:///tmp/toonHomeWizardBatteries.list"
  property string checkResultFile : "file:///tmp/toonHomeWizardBatteries.checkResult"
  property string tokenFile : "file:///tmp/toonHomeWizardBatteries.token"
  property variant controlJSON : {}

  FileIO {
    id: livesignal
    source : "file:///tmp/toonHomeWizardBatteries.timestamp"
   }
  property string timestamp

  FileIO {
    id: dataFile
    source : "file:///tmp/toonHomeWizardBatteries.data"
   }

// -------- Function controlToonHomeWizardBatteriesProcess

  function createScript() {
    controlFile.source = "file:///qmf/qml/apps/toonHomeWizard/ToonHomeWizardApp.qml"
    var script = controlFile.read()
    var marker = "*" + "###" + "*"
    script = script.substring(script.indexOf(marker)+marker.length+1)
    script = script.substring(0,script.indexOf(marker))
    controlFile.source = "file:///qmf/qml/apps/toonHomeWizard/toonHomeWizard.sh"
    controlFile.write(script)
  }

  function controlToonHomeWizardBatteriesProcess(control) {
    debug && log("controlToonHomeWizardBatteriesProcess control: "+control)
    switch ( control ) {
      case "Start":
        createScript()
        controlToonHomeWizardBatteriesProcess("List")
        controlFile.source = cmdFile
        controlFile.write("start")
        controlFile.source = triggerFile
        controlFile.write(triggerText)
        break
      case "Stop":
        controlFile.source = cmdFile
        controlFile.write("exit")
        break
      case "List":
        var ii = 0
        var list =""
        for (ii = 0; ii < 4; ii++) {
          if ( batteryActive[ii] && (list.indexOf(batteryIP[ii]) == -1) ) {
            list=list+batteryIP[ii]+" "+batteryToken[ii]+"\n"
          }
        }
        controlFile.source = lstFile
        controlFile.write(list)
        break
      case "CheckResult":
        try {
          controlFile.source = checkResultFile
          controlJSON = JSON.parse(controlFile.read());
          if ('TOKEN' in controlJSON ) {
            return controlJSON['TOKEN']
          } else {
            return "No TOKEN in file"
          }
        } catch(e) {
          return "File Not Found"
        }
        break
      case "TokenResult":
        try {
          controlFile.source = tokenFile
          controlJSON = JSON.parse(controlFile.read());
          if ('token' in controlJSON ) {
            return controlJSON['token']
          } else {
            return "No TOKEN in file"
          }
        } catch(e) {
          return "File Not Found"
        }
        break
      default:
        var action=control.split("_")[0]
        var actionIP=control.split("_")[1]
        switch (action) {
        case "Check":
          var actionTOKEN=control.split("_")[2]
          var ii = 0
          var cmd = action + " " + actionIP +" " + actionTOKEN
          for (ii = 0; ii < batteryTokenHistory.length; ii++) {
            cmd = cmd + " " + batteryTokenHistory[ii]
          }
          controlFile.source = cmdFile
          controlFile.write(cmd)
          break
        case "LogIn":
          var cmd = "getToken " + actionIP
          debug && log(cmd)
          controlFile.source = cmdFile
          controlFile.write(cmd)
          break
        case "LogOut":
          var actionTOKEN=control.split("_")[2]
          var cmd = "delToken " + actionIP + " " + actionTOKEN
          debug && log(cmd)
          controlFile.source = cmdFile
          controlFile.write(cmd)
          break
        }
    }
  }

// -------- Function checkToonHomeWizardBatteriesProcessAge

  property variant timestampJSON : {}

  function checkToonHomeWizardBatteriesProcessAge() {
    // return age of last timestamp in seconds or 99999 in case of error
    try {
      timestampJSON = JSON.parse(livesignal.read());
      if ('timestamp' in timestampJSON ) {
        timestamp = timestampJSON['timestamp']
      } else {
        log("No timestamp in JSON");
        return 99999
      }
      var now = Math.floor(Date.now() / 1000);
      var ageSeconds = now - timestamp;
      return ageSeconds
    } catch(e) {
      log("checkToonHomeWizardBatteriesProcessAge : Process probably (still) dead: "+e);
      return 99999
    }
  }

// -------- Function controlToonHomeWizardBatteriesProcess

  property variant batteryDataJSON

  function readToonHomeWizardBatteriesData() {
    if ( batteriesInApp ) {
      try {
        batteryDataJSON = JSON.parse(dataFile.read())
        var ii = 0
        for ( ii = 0 ; ii < 4; ii++) {
          if ( ( batteryIP[ii] in batteryDataJSON ) && batteryActive[ii] ){

            batteryLevel[ii]=batteryDataJSON[batteryIP[ii]]['measurement']['state_of_charge_pct']
            batteryWatts[ii]=batteryDataJSON[batteryIP[ii]]['measurement']['power_w']
            batteryKWHImport[ii]=batteryDataJSON[batteryIP[ii]]['measurement']['energy_import_kwh']
            batteryKWHExport[ii]=batteryDataJSON[batteryIP[ii]]['measurement']['energy_export_kwh']

            battery_wifi[ii]=batteryDataJSON[batteryIP[ii]]['system']['wifi_rssi_db']

            batteryOke[ii] = true
          } else {
            batteryOke[ii] = ! batteryActive[ii]
          }
        }
      } catch(e) {
        log("readToonHomeWizardBatteriesData : Process probably (still) dead: "+e);
      }
    }
  }

  Timer {
    id: getHomeWizardBatteriesTimer
    interval: 10000 // syncIntervalms
    running: ( activeMe ) // Tile not installed -> do not run -> no CPU waste
    repeat: true
    triggeredOnStart: true
    onTriggered: {
      if ( batteriesInApp && ! settingsActive ) {
        if ( checkToonHomeWizardBatteriesProcessAge() >  60 ) {
          log("getHomeWizardBatteriesTimer starts background process...")
          controlToonHomeWizardBatteriesProcess("Start")
        } else {
          readToonHomeWizardBatteriesData()
          homeWizardScreen2.updateScreenData()
        }
      }
    }
  }

}

// ---- End of APP



































































































/*
*###*
#!/bin/sh
#
#   File    : toonHomeWizard.sh
#   Purpose : Interface HomeWizard Thuisbatterijen
#
# make sure we have a sane environment
. /etc/profile
#
debug=false
debug=true
cmd=/tmp/toonHomeWizardBatteries.cmd
livesignal=/tmp/toonHomeWizardBatteries.timestamp
log=/dev/null
$debug && log=/tmp/toonHomeWizardBatteries.log
# function which is called at the end of this script
do_it () {
  #
  echo "---------------------------"  >> $log 2>&1
  echo "$(date '+%d/%m/%Y %H:%M:%S') Start Up"  >> $log 2>&1
  if [[ "$(uname -m)" == "armv7l" ]] ; then
    # Toon 2
    sleeptime=5
  else
    # Toon 1
    sleeptime=5
  fi
  while true # read and execute commands
  do
    echo '{"timestamp" : '$(date +%s)'}' > $livesignal
    if [ -f $cmd ] ; then
      cmdLine=$(cat $cmd)
      todo=$(echo ${cmdLine} | cut -d" " -f 1)
#      echo "$(date '+%d/%m/%Y %H:%M:%S') cmdLine: $cmdLine"  >> $log 2>&1
    else
      todo="collectBatteryData"
    fi
    case $todo in
      start)
        rm $cmd
#        echo "$(date '+%d/%m/%Y %H:%M:%S') Start" >> $log 2>&1
        rm "$0"
        ;;
      exit)
        echo  "$(date '+%d/%m/%Y %H:%M:%S') Exit"  >> $log 2>&1
        echo "---------------------------"  >> $log 2>&1
        sleep 3
        rm /tmp/toonHomeWizardBatteries*
        exit
        ;;
      collectBatteryData)
        lst=/tmp/toonHomeWizardBatteries.list # IP key combinations to collect data from
        if [ -f $lst ] ; then
          btdt=/tmp/toonHomeWizardBatteries.data_tmp # all battery data temp file
          btd=/tmp/toonHomeWizardBatteries.data # all battery data
          json="{"
          while read -r IP TOKEN
          do
            systemdata=$(curl --connect-timeout 4 -s \
                "https://$IP/api/system" \
                --insecure \
                -H "Authorization: Bearer $TOKEN" \
                -H "X-Api-Version: 2")
            success=$(echo $systemdata | grep wifi_ssid | wc -l)
            if [ $success == 1 ] ; then
              measurementdata=$(curl --connect-timeout 4 -s \
                  "https://$IP/api/measurement" \
                  --insecure \
                  -H "Authorization: Bearer $TOKEN" \
                  -H "X-Api-Version: 2")
              success=$(echo $measurementdata | grep energy_import_kwh | wc -l)
              if [ $success == 1 ] ; then
                jsonBattery='"'$IP'":{'

                jsonBattery=$jsonBattery'"system":'
                jsonBattery=$jsonBattery$systemdata

                jsonBattery=$jsonBattery','

                jsonBattery=$jsonBattery'"measurement":'
                jsonBattery=$jsonBattery$measurementdata

                jsonBattery=$jsonBattery'}'
                if [ "$json" != "{" ] ; then # not first to add
                  json=$json','$jsonBattery
                else
                  json=$json$jsonBattery
                fi
              else
                echo "$(date '+%d/%m/%Y %H:%M:%S') No measurementdata data for: $IP"  >> $log 2>&1
              fi
            else
              echo "$(date '+%d/%m/%Y %H:%M:%S') No system data for: $IP"  >> $log 2>&1
            fi
            sleep 1
          done < "$lst"
          json=$json'}'
          echo $json>$btdt
          mv $btdt $btd
        fi
        ;;
      Check)
        rm $cmd
        checkResulttmp=/tmp/toonHomeWizardBatteries.checkResulttmp
        checkResult=/tmp/toonHomeWizardBatteries.checkResult
        IP=$(echo ${cmdLine} | cut -d" " -f 2)
        Tokens=$(echo ${cmdLine} | cut -d" " -f 3-)
        unauthorizedFound=0
        valid=0
        for TOKEN in $Tokens
        do
          case "$TOKEN" in
            [0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f]\
[0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f]\
[0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f]\
[0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f]\
[0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f]\
[0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f]\
[0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f]\
[0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f])
            echo "$(date '+%d/%m/%Y %H:%M:%S') Check Token: $TOKEN"  >> $log 2>&1
            measurementdata=$(curl --connect-timeout 4 -s \
                "https://$IP/api/measurement" \
                --insecure \
                -H "Authorization: Bearer $TOKEN" \
                -H "X-Api-Version: 2")
            unauthorizedFound=$(echo $measurementdata | grep "user:unauthorized" | wc -l)
            valid=$(echo $measurementdata | grep energy_import_kwh | wc -l)
            if [ $valid == 1 ] ; then
              break
            fi
            ;;
          esac
        done
        if [ $valid == 1 ] ; then
          echo "{\"TOKEN\" : \"$TOKEN\"}">$checkResulttmp
        elif [ $unauthorizedFound == 1 ] ; then
          echo "{\"TOKEN\" : \"unauthorized\"}">$checkResulttmp
          echo "$(date '+%d/%m/%Y %H:%M:%S') Check Token unauthorized for : $IP"  >> $log 2>&1
        else
          echo "{\"TOKEN\" : \"invalidIP\"}">$checkResulttmp
          echo "$(date '+%d/%m/%Y %H:%M:%S') Check Token invalid IP : $IP"  >> $log 2>&1
        fi
        mv $checkResulttmp $checkResult
        sleep 5 # app checks every second so file can be deleted after 5
        rm $checkResult
        ;;
      getToken)
        rm $cmd
        # expect:
        # '{"error":"user:creation-not-enabled"}'
        # {"token":"1234567890ABCDEF1234567890ABCDEF","name":"local/new_user"}
        IP=$(echo ${cmdLine} | cut -d" " -f 2)
        tokenFiletmp=/tmp/toonHomeWizardBatteries.tokentmp
        tokenFile=/tmp/toonHomeWizardBatteries.token
        # create username Toon_<mac address of your Toon>
        mac=$(cat /sys/class/net/wlan0/address | tr -d ":")
        ToonUser="Toon_$mac"
        JSON=$(printf '{"name":"local/%s"}' "$ToonUser")
        NoTokenYet='{"error":"user:creation-not-enabled"}'
        Token="$NoTokenYet"
        counter=30
        while [[ "$Token" == "$NoTokenYet" ]] && [[ "$counter" != "0" ]]
        do
          echo "$counter"  >> $log 2>&1
          sleep 1
          Token=$(curl --connect-timeout 4 -s "https://$IP/api/user" \
              --insecure \
              -X POST \
              -H "Content-Type: application/json" \
              -H "X-Api-Version: 2" \
              -d "$JSON")
          counter=$((counter - 1))
        done
        echo "$Token" > $tokenFiletmp
        mv $tokenFiletmp $tokenFile
        echo "$(date '+%d/%m/%Y %H:%M:%S') Got Token: $Token"  >> $log 2>&1
        sleep 5 # app checks every 2 seconds so file can be deleted after 5  >> $log 2>&1
        rm $tokenFile
        ;;
      delToken)
        rm $cmd
        lsttmp=/tmp/toonHomeWizardBatteries.listtmp
        lst=/tmp/toonHomeWizardBatteries.list
        IP=$(echo ${cmdLine} | cut -d" " -f 2)
        grep $lst -v -e $IP > $lsttmp
        mv $lsttmp $lst
        TOKEN=$(echo ${cmdLine} | cut -d" " -f 3)
        mac=$(cat /sys/class/net/wlan0/address | tr -d ":")
        ToonUser="Toon_$mac"
        echo "$(date '+%d/%m/%Y %H:%M:%S') Delete $IP $TOKEN $ToonUser"  >> $log 2>&1
        JSON=$(printf '{"name":"local/%s"}' "$ToonUser")
        echo "$(date '+%d/%m/%Y %H:%M:%S') Delete $JSON"  >> $log 2>&1
        returnCode=$(curl --connect-timeout 4 -s "https://$IP/api/user" \
            --insecure \
            -X DELETE \
            -H "Authorization: Bearer $TOKEN" \
            -H "Content-Type: application/json" \
            -H "X-Api-Version: 2" \
            -d "$JSON")
        echo "$(date '+%d/%m/%Y %H:%M:%S') Delete returnCode should be empty : \"$returnCode\""  >> $log 2>&1
        ;;
      *)
        echo "$(date '+%d/%m/%Y %H:%M:%S') Command not supported: $cmdLine"  >> $log 2>&1
        rm $cmd
        ;;
    esac
    if [[ "$todo" != "start" ]]  ; then sleep $sleeptime ; fi
  done
}

# Controleer of er meer dan 1 instantie draait
COUNT=$(ps -ef | grep /qmf/qml/apps/toonHomeWizard/toonHomeWizard.sh | grep -v grep | wc -l)
if [ $COUNT -gt 2 ]; then
  echo "$(date '+%d/%m/%Y %H:%M:%S') Avoid second startup "  >> $log 2>&1
else
  rm $log
  do_it
fi
*###*
*/
